#!/bin/sh

set -o errexit

echo "Building example programs..."
cmake -B build -S .
cmake --build build

echo "\nWriting Header V1 to file..."
./build/write

echo "\nReading file with Header V1:"
./build/read-v1

echo "\nReading file with Header V2:"
./build/read-v2

echo "\nReading file with Header Both:"
./build/read-both
