_default:
    just --list --justfile {{ justfile() }}

configure:
    denv cmake -B build -S .
    mkdir data

build:
    denv cmake --build build

clean:
    rm -r build data

copy:
    denv ./build/copy data/output.root data/copy-output.root

_read v file:
    denv ./build/read-{{v}} {{file}}

write: 
    denv ./build/write data/output.root

read-v1 file: (_read "v1" file)
read-v2 file: (_read "v2" file)
