@_default:
    just --list --justfile {{ justfile() }}

# clone root
clone:
    git clone git@github.com:tomeichlersmith/root.git src
    git -C src origin add upstream git@github.com:root-project/root.git

# configure root build
configure:
    /usr/bin/cmake \
      -B build \
      -S src \
      -DCMAKE_BUILD_TYPE=Debug \
      -Dtesting=ON \
      -Dminimal=ON

_build *args:
    /usr/bin/cmake --build build -- {{args}}

# compile with 2 cores
build: _build "-j2"

test-all *args:
    cd build && /usr/bin/ctest {{args}}

test-evolution:
    ./build/tree/tree/test/evolution
